#!/bin/bash

# push code upstream

if ! echo "$(git branch)" | grep '\* master' 2>&1 >/dev/null; then
  git push origin HEAD $@
else
  echo 'You cannot push to master so conveniently. use "git push origin HEAD"'.
fi
