#!/bin/bash

if ! [ -d ./.git ]; then
  echo "You are not in a git repository" 1>&2
fi

CHECKED_BRANCH=$(git branch | grep '^\*' | cut -d' ' -f 2)

if [ -z "$1" ]; then
  BRANCH=master
else
  BRANCH="$1"
fi

git checkout "$BRANCH"
git pull
git checkout "$CHECKED_BRANCH"
git rebase "$BRANCH"
