#!/bin/bash

if ! [ -d ./.git ]; then
  echo "You are not in a git repository" 1>&2
fi

BRANCH=$(git branch | grep '^\*' | cut -d' ' -f 2)

git checkout master
git pull
git checkout $BRANCH
git rebase master
